# Generated by Django 5.0.6 on 2024-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantthread',
            name='assistant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assistantthread',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
